name: Run dbt Models

on:
  push:
    branches:
      - main
  schedule:
    - cron: '0 6 * * *'  # Runs daily at 6 AM UTC

jobs:
  dbt-run:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v2

      - name: Install dbt
        run: pip install dbt-postgres

      - name: Create dbt profiles directory
        run: mkdir -p ~/.dbt

      - name: Generate dbt profiles.yml
        run: |
          echo "ecommerce_project:" > ~/.dbt/profiles.yml
          echo "  target: dev" >> ~/.dbt/profiles.yml
          echo "  outputs:" >> ~/.dbt/profiles.yml
          echo "    dev:" >> ~/.dbt/profiles.yml
          echo "      type: postgres" >> ~/.dbt/profiles.yml
          echo "      host: ${{ secrets.DB_HOST }}" >> ~/.dbt/profiles.yml
          echo "      user: ${{ secrets.DB_USER }}" >> ~/.dbt/profiles.yml
          echo "      password: ${{ secrets.DB_PASSWORD }}" >> ~/.dbt/profiles.yml
          echo "      port: 5432" >> ~/.dbt/profiles.yml
          echo "      dbname: ${{ secrets.DB_NAME }}" >> ~/.dbt/profiles.yml
          echo "      schema: public" >> ~/.dbt/profiles.yml

      - name: Run dbt
        run: dbt run --profiles-dir ~/.dbt
