name: Run dbt Models

on:
  push:
    branches:
      - main
  schedule:
    - cron: '0 6 * * *'  # Runs daily at 6 AM UTC

jobs:
  dbt-run:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v2

      - name: Install dbt
        run: pip install dbt-postgres

      - name: Create dbt profiles directory
        run: mkdir -p ~/.dbt

      - name: Generate dbt profiles.yml
        run: |
          cat << EOF > ~/.dbt/profiles.yml
          ecommerce_project:
            target: dev
            outputs:
              dev:
                type: postgres
                host: ${{ secrets.DB_HOST }}
                user: ${{ secrets.DB_USER }}
                password: ${{ secrets.DB_PASSWORD }}
                port: 5432
                dbname: ${{ secrets.DB_NAME }}
                schema: public
          EOF

      - name: Verify profiles.yml
        run: cat ~/.dbt/profiles.yml  # Sprawdzenie, czy plik istnieje

      - name: Run dbt
        run: dbt run --profiles-dir ~/.dbt
