name: Run dbt Models

on:
  push:
    branches:
      - main
  schedule:
    - cron: '0 6 * * *'  # Runs daily at 6 AM UTC

jobs:
  dbt-run:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v2

      - name: Install dbt
        run: pip install dbt-postgres

      - name: Debug – Check Home Directory
        run: ls -la /home/runner/

      - name: Create dbt profiles directory
        run: mkdir -p /home/runner/.dbt

      - name: Debug – Check if .dbt Exists
        run: ls -la /home/runner/

      - name: Generate dbt profiles.yml
        run: |
          cat << EOF > /home/runner/.dbt/profiles.yml
          ecommerce_project:
            target: dev
            outputs:
              dev:
                type: postgres
                host: ${{ secrets.DB_HOST }}
                user: ${{ secrets.DB_USER }}
                password: ${{ secrets.DB_PASSWORD }}
                port: 5432
                dbname: ${{ secrets.DB_NAME }}
                schema: public
          EOF

      - name: Debug – Check profiles.yml
        run: cat /home/runner/.dbt/profiles.yml

      - name: Run dbt
        run: dbt run --profiles-dir /home/runner/.dbt
