name: Run dbt Models Locally

on:
  workflow_dispatch:  # Only runs manually

jobs:
  dbt-run:
    runs-on: self-hosted  # Runs on your local machine instead of GitHub Actions

    steps:
      - name: Checkout repo
        uses: actions/checkout@v2

      - name: Install dependencies (Only if needed)
        run: |
          echo "Ensure PostgreSQL and dbt are installed locally."
          echo "Skip installation if already set up."

      - name: Create dbt profiles directory
        run: mkdir -p ~/.dbt

      - name: Generate dbt profiles.yml (for local setup)
        run: |
          echo "ecommerce_project:" > ~/.dbt/profiles.yml
          echo "  target: dev" >> ~/.dbt/profiles.yml
          echo "  outputs:" >> ~/.dbt/profiles.yml
          echo "    dev:" >> ~/.dbt/profiles.yml
          echo "      type: postgres" >> ~/.dbt/profiles.yml
          echo "      host: localhost" >> ~/.dbt/profiles.yml
          echo "      user: postgres" >> ~/.dbt/profiles.yml
          echo "      password: my_local_password" >> ~/.dbt/profiles.yml  # Change this to your local password
          echo "      port: 5432" >> ~/.dbt/profiles.yml
          echo "      dbname: ecommerce_db" >> ~/.dbt/profiles.yml
          echo "      schema: public" >> ~/.dbt/profiles.yml

      - name: Skip Connection Test (Running Locally)
        run: echo "Skipping connection test since DB is local."

      - name: Run dbt Locally
        run: dbt run --profiles-dir ~/.dbt

