name: Run dbt Models

on:
  push:
    branches:
      - main
  schedule:
    - cron: '0 6 * * *'  # Runs daily at 6 AM UTC

jobs:
  dbt-run:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v2

      - name: Install dbt
        run: pip install dbt-postgres

      - name: Run dbt
        run: dbt run
